/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2024 MediaTek Inc.
 */

#ifndef __DT_BINDINGS_PINCTRL_MT6739_PINFUNC_H
#define __DT_BINDINGS_PINCTRL_MT6739_PINFUNC_H

#define PINMUX_GPIO(gpio, func) gpio func

/* UART0 pins */
#define PINMUX_GPIO20__FUNC_UART0TX		PINMUX_GPIO(20, 2)
#define PINMUX_GPIO21__FUNC_UART0RX		PINMUX_GPIO(21, 2)

/* UART1 pins */  
#define PINMUX_GPIO20__FUNC_UART1RX		PINMUX_GPIO(20, 6)
#define PINMUX_GPIO21__FUNC_UART1TX		PINMUX_GPIO(21, 6)

/* MSDC0 (eMMC) pins */
#define PINMUX_GPIO38__FUNC_MSDC0_CMD		PINMUX_GPIO(38, 1)
#define PINMUX_GPIO39__FUNC_MSDC0_DSL		PINMUX_GPIO(39, 1)
#define PINMUX_GPIO40__FUNC_MSDC0_CLK		PINMUX_GPIO(40, 1)
#define PINMUX_GPIO41__FUNC_MSDC0_DAT0		PINMUX_GPIO(41, 1)
#define PINMUX_GPIO42__FUNC_MSDC0_DAT1		PINMUX_GPIO(42, 1)
#define PINMUX_GPIO43__FUNC_MSDC0_DAT2		PINMUX_GPIO(43, 1)
#define PINMUX_GPIO44__FUNC_MSDC0_DAT3		PINMUX_GPIO(44, 1)
#define PINMUX_GPIO45__FUNC_MSDC0_DAT4		PINMUX_GPIO(45, 1)
#define PINMUX_GPIO46__FUNC_MSDC0_DAT5		PINMUX_GPIO(46, 1)
#define PINMUX_GPIO47__FUNC_MSDC0_DAT6		PINMUX_GPIO(47, 1)
#define PINMUX_GPIO48__FUNC_MSDC0_DAT7		PINMUX_GPIO(48, 1)
#define PINMUX_GPIO49__FUNC_MSDC0_RSTB		PINMUX_GPIO(49, 1)

/* MSDC1 (SD card) pins */
#define PINMUX_GPIO71__FUNC_MSDC1_CMD		PINMUX_GPIO(71, 1)
#define PINMUX_GPIO72__FUNC_MSDC1_CLK		PINMUX_GPIO(72, 1)
#define PINMUX_GPIO73__FUNC_MSDC1_DAT0		PINMUX_GPIO(73, 1)
#define PINMUX_GPIO74__FUNC_MSDC1_DAT1		PINMUX_GPIO(74, 1)
#define PINMUX_GPIO75__FUNC_MSDC1_DAT2		PINMUX_GPIO(75, 1)
#define PINMUX_GPIO76__FUNC_MSDC1_DAT3		PINMUX_GPIO(76, 1)

/* I2C pins - Add more as needed based on pin functions available */
/* SPI pins - Add more as needed based on pin functions available */
/* USB pins - Add more as needed based on pin functions available */

#endif /* __DT_BINDINGS_PINCTRL_MT6739_PINFUNC_H */